### PR TITLE
Support Vaadin 22

### LINKED ISSUE #4: Update for Vaadin 22
With Vaadin 22 beeing a new LTS, would it be possible to update this to be compatible with Vaadin 22?

Currently it is incompatible because on an import and depending logic on `vaadin-dialog`.
Specifically in vcf-enhanced-dialog.js:8 `import { getMouseOrFirstTouchEvent } from '@vaadin/vaadin-dialog/src/vaadin-dialog-utils';`.

Changing to `@vaadin/dialog/src/vaadin-dialog-utils` seems to fix the incompatibility,

### PR DESCRIPTION
**Pull request by hfazai**
Fixes #4

### CODE REVIEW

**Comment by niiyeboah** [comment]
@hfazai This looks good 👍 

There is one issue though, I tried to run the demo locally (`npm start` script) with these changes but this warning can be seen in the console:
```
WARNING: <template> inside <vcf-enhanced-dialog> is no longer supported. Import @vaadin/polymer-legacy-adapter/template-renderer.js to enable compatibility.
```
Also no content is shown in the first two examples.

If you add the import like they say:
```
import '@vaadin/polymer-legacy-adapter/template-renderer.js';
```
This adds some public APIs which enable the template renderer functionality and should fix the demo. We could then later update the demos to no longer use the template syntax.

**Comment by hfazai** [comment]
@niiyeboah 
I added the import and the demo works fine now.
Thanks for the review :+1:

**Comment by hfazai** [comment]
@niiyeboah Let me know if I need to change something else.

**Comment by kkleinwi** [comment]
Will someone be pushing a new release to the Vaadin Addon repository?

**Comment by hfazai** [comment]
@kkleinwi 
Try using this, while waiting for the new release:
````Kotlin
@NpmPackage(value = "@vaadin-component-factory/vcf-enhanced-dialog", version = "22.0.6")
open class EnhancedDialog22 : EnhancedDialog()
````

**Pull request merged**
